# Site settings
title: Merouane Atig
author: Merouane Atig
description: Personal blog and resume
avatar: profile.jpg
baseurl: ""
url: "https://patem.net" # the base hostname & protocol for your site
email: merwan@patem.net
github:  merwan
twitter: merwanat
linkedin: merwanat
stackoverflow: users/172991/merwan
google_analytics: UA-48359436-1

# Build settings
markdown: kramdown
kramdown:
  input: GFM
