# Site settings
title: Merouane Atig
author: Merouane Atig
description: Personal blog and resume
avatar: profile.jpg
baseurl: ""
url: "https://patem.net" # the base hostname & protocol for your site
email: merwan@patem.net
github:  https://github.com/merwan
mastodon: https://piaille.fr/@merwanat
linkedin: https://linkedin.com/in/merouaneatig
stackoverflow: https://stackoverflow.com/users/172991/merwan

# Build settings
markdown: kramdown
kramdown:
  input: GFM
